/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { Color, Depth, Fresnel, LayerMaterial } from "lamina";

export default function Model(props) {
  const mesh = useRef();

  const { nodes, materials } = useGLTF("./stellaLogo.glb");

  useFrame((state, delta) => {
    mesh.current.rotation.y += delta / 2;
  });
  return (
    <>
      <group {...props} dispose={null}>
        <mesh
          ref={mesh}
          geometry={nodes.STELLA_LOGO_3D003001.geometry}
          material={materials.Material}
          scale={3}
        />
      </group>
    </>
  );
}

useGLTF.preload("/stellaLogo.glb");
